service:
  name: nodejsAppService
  identifier: nodejsAppService
  serviceDefinition:
    type: Kubernetes
    spec:
      artifacts:
        primary:
          type: DockerRegistry
          spec:
            connectorRef: awsECRConnector
            imagePath: 590183810689.dkr.ecr.ap-south-1.amazonaws.com/nodejs-app
            tag: latest
      manifests:
        - manifest:
            identifier: nodeAppManifest
            type: K8sManifest
            spec:
              store:
                type: Git
                spec:
                  connectorRef: gitConnector
                  repoName: nodejs-eks-harness
                  paths:
                    - k8s/deployment.yaml
